language: generic

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode7.2

before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start

before_install:
    # Required by Buildozer Android
    # https://buildozer.readthedocs.io/en/latest/installation.html#android-on-ubuntu-12-04-64bit
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; sudo apt-get update -q          ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; sudo apt-get install build-essential ccache git lib32z1 lib32bz2-1.0 libncurses5:i386 libstdc++6:i386 python2.7 python2.7-dev openjdk-7-jdk unzip zlib1g-dev zlib1g:i386       ; fi
    # Required by Kivy
    # https://kivy.org/docs/installation/installation-linux.html#dependencies-with-sdl2
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; sudo apt-get install python-pip build-essential git python-dev ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; sudo apt-get install libegl1-mesa-dev libgles2-mesa-dev libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev ; fi
    # Optional dependency for the cut and multitouch support
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; sudo apt-get install xclip libmtdev1 ;fi
    # Required for the project

install:
    - sudo -H pip install coveralls

env:
    global:
        - COVERALLS_PARALLEL=true
    matrix:
        #- SCRIPT_COMMAND="./travis/script_linux.sh"
        - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; SCRIPT_COMMAND="./travis/script_android.sh" ;fi

script:
    # runs in parallel
    - (eval "$SCRIPT_COMMAND")

#after_success:
#    - coveralls
